name: show_caseview_csx
description: A mask for novice guides.
version: 0.0.1
homepage: https://github.com/KirstenDunst/FlutterPlugins/tree/main/show_caseview_csx
publish_to: https://dart-pub.brainco.cn/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/images/
