name: common_plugin_csx
description: A small collection of generic plug-ins.
version: 0.0.1
homepage: https://github.com/KirstenDunst/FlutterPlugins/tree/main/common_plugin_csx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.csx.common_plugin_csx
        pluginClass: CommonPluginCsxPlugin
      ios:
        pluginClass: CommonPluginCsxPlugin
