name: hot_fix_csx
description: The update of the project's large resource pack does not require the repair tool of the app's re-release.
version: 0.0.8+4
homepage: https://github.com/KirstenDunst/FlutterPlugins/tree/main/hot_fix_csx
publish_to: https://dart-pub.brainco.cn/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  path_provider: ^2.0.1
  common_plugin_csx: ^0.0.2
  package_info_plus: ^1.4.2
  permission_handler: ^9.2.0
  connectivity_plus: ^2.3.0
  sqflite: ^2.0.2+1
  bot_toast: ^4.0.1
  stack_trace: ^1.10.0
  dio: ^4.0.6
  async: ^2.8.2
  flutter_downloader: ^1.7.3
  path: ^1.8.0
  archive: ^3.3.0
  convert: ^3.0.1
  crypto: ^3.0.1
  synchronized: ^3.0.0+2

  flutter_utils:
    hosted:
      name: flutter_utils
      url: https://dart-pub.brainco.cn/
    version: ^1.1.2
  flutter_network:
    hosted:
      name: flutter_network
      url: https://dart-pub.brainco.cn/
    version: ^2.0.4
  device_info_enhanced:
    hosted:
      name: device_info_enhanced
      url: https://dart-pub.brainco.cn/
    version: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.csx.hotfix.hot_fix_csx
        pluginClass: HotFixCsxPlugin
      ios:
        pluginClass: HotFixCsxPlugin
