name: hot_fix_csx
description: The update of the project's large resource pack does not require the repair tool of the app's re-release.
version: 0.0.1
homepage: https://github.com/KirstenDunst/FlutterPlugins/tree/main/hot_fix_csx

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.1
  ffi: ^1.1.2
  path_provider: ^2.0.1
  archive: ^3.1.8
  common_plugin_csx: ^0.0.1
  shared_preferences: ^2.0.12
  permission_handler: ^8.3.0
  get: ^4.6.1

  logger_util:
    hosted:
      name: logger_util
      url: https://dart-pub.brainco.cn/
    version: ^1.0.4
  flutter_network:
    hosted:
      name: flutter_network
      url: https://dart-pub.brainco.cn/
    version: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.csx.hotfix.hot_fix_csx
        pluginClass: HotFixCsxPlugin
      ios:
        pluginClass: HotFixCsxPlugin

