name: hot_fix_csx
description: The update of the project's large resource pack does not require the repair tool of the app's re-release.
version: 0.0.1
homepage: https://github.com/KirstenDunst/FlutterPlugins/tree/main/hot_fix_csx
publish_to: https://dart-pub.brainco.cn/

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  path_provider: ^2.0.1
  common_plugin_csx: ^0.0.2
  package_info_plus: ^1.4.2
  permission_handler: ^9.2.0
  connectivity_plus: ^2.3.0
  sqflite: ^2.0.2+1
  bot_toast: ^4.0.1
  stack_trace: ^1.10.0

  logger_util:
    hosted:
      name: logger_util
      url: https://dart-pub.brainco.cn/
    version: ^1.0.4
  flutter_network:
    hosted:
      name: flutter_network
      url: https://dart-pub.brainco.cn/
    version: ^2.0.4

dependency_overrides:
  flutter_downloader:
    hosted:
      name: flutter_downloader
      url: https://dart-pub.brainco.cn/
    version: ^1.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.csx.hotfix.hot_fix_csx
        pluginClass: HotFixCsxPlugin
      ios:
        pluginClass: HotFixCsxPlugin
